#!/bin/bash

set -e

DOCKER=`which docker`
docker_image="cloudkats/node"
tag="8"

build_docker() {
    echo "> Build docker with Node"

    if [ -z "$DOCKER" ];then
        echo Could not find the 'docker' executable
        exit 1
    fi
    $DOCKER build -t $docker_image:$tag ../node
    echo "$docker_image ready"
}

push() {
    docker push $docker_image:$tag
}

build_docker
push